In [10]:
#Importing the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime
from pypfopt.efficient_frontier import EfficientFrontier
from pypfopt import risk_models
from pypfopt import expected_returns
from pypfopt.discrete_allocation import DiscreteAllocation, get_latest_prices
import yfinance as yf

In [11]:
Nifty50 = ['HINDALCO.NS', 'TATASTEEL.NS', 'JSWSTEEL.NS', 'TATAMOTORS.NS', 'ONGC.NS', 'ASIANPAINT.NS', 'WIPRO.NS', 'DIVISLAB.NS', 'LT.NS', 'ADANIENT.NS', 'ADANIPORTS.NS', 'BAJAJ-AUTO.NS', 'BAJFINANCE.NS', 'EICHERMOT.NS', 'ICICIBANK.NS', 'GRASIM.NS', 'INFY.NS', 'TECHM.NS', 'TITAN.NS', 'SBIN.NS', 'RELIANCE.NS', 'MARUTI.NS', 'INDUSINDBK.NS', 'BHARTIARTL.NS', 'AXISBANK.NS', 'BPCL.NS', 'HEROMOTOCO.NS', 'HCLTECH.NS', 'ULTRACEMCO.NS', 'KOTAKBANK.NS', 'TATACONSUM.NS', 'POWERGRID.NS', 'COALINDIA.NS', 'TCS.NS', 'BAJAJFINSV.NS', 'DRREDDY.NS', 'CIPLA.NS', 'UPL.NS', 'HDFCBANK.NS', 'HDFC.NS', 'SUNPHARMA.NS', 'HDFCLIFE.NS', 'SBILIFE.NS', 'BRITANNIA.NS', 'NTPC.NS', 'ITC.NS', 'M&M.NS', 'NESTLEIND.NS', 'APOLLOHOSP.NS', 'HINDUNILVR.NS']

In [12]:
stockStartDate = '2015-01-01'
today = datetime.today().strftime('%Y-%m-%d')

In [13]:
#Importing the data
df = pd.DataFrame()

for stock in Nifty50:
    df[stock] = yf.download(stock, data_source=' yahoo', start= stockStartDate, end= today)['Adj Close']

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [14]:
df

,HINDALCO.NS,TATASTEEL.NS,JSWSTEEL.NS,TATAMOTORS.NS,ONGC.NS,ASIANPAINT.NS,WIPRO.NS,DIVISLAB.NS,LT.NS,ADANIENT.NS,...,SUNPHARMA.NS,HDFCLIFE.NS,SBILIFE.NS,BRITANNIA.NS,NTPC.NS,ITC.NS,M&M.NS,NESTLEIND.NS,APOLLOHOSP.NS,HINDUNILVR.NS
Date,,,,,,,,,,,,,,,,,,,,,
2015-01-01,149.564362,14.594913,88.688507,492.960724,155.133560,709.613770,195.379028,814.255798,872.795166,70.727570,...,780.251099,NaN,NaN,811.325806,83.845085,195.391037,574.012756,5647.145020,1093.238525,663.048523
2015-01-02,151.121841,14.822253,88.958900,506.163696,157.455719,734.146851,197.112106,817.731201,891.203979,71.074005,...,784.094421,NaN,NaN,832.168152,84.992844,196.003067,568.259033,5659.257324,1095.131714,660.862976
2015-01-05,148.054092,15.036964,88.746742,518.031555,159.236755,734.099426,197.465805,812.809631,903.602417,72.250389,...,784.568970,NaN,NaN,832.744019,84.757408,196.774734,565.382080,5662.295410,1098.773193,664.665955
2015-01-06,144.797562,14.308028,85.510056,495.878235,150.218704,716.575806,192.850113,780.994202,873.462891,71.701881,...,767.297546,NaN,NaN,833.652100,81.932167,191.718994,562.226807,5583.550293,1066.050781,677.254639
2015-01-07,140.549927,14.033776,84.191246,488.411377,152.428131,730.973694,191.382294,769.564880,871.372253,71.066772,...,768.483704,NaN,NaN,884.085938,83.903961,188.153351,568.027039,5606.923828,1074.401367,701.033264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-22,455.500000,107.650002,737.549988,394.450012,142.250000,3088.550049,388.750000,3495.899902,2109.949951,3868.550049,...,1010.650024,577.849976,1244.750000,4391.450195,165.899994,332.450012,1233.949951,20306.599609,4781.700195,2645.350098
2022-12-23,429.549988,102.250000,727.849976,378.350006,139.800003,3057.899902,377.649994,3498.449951,2062.750000,3642.199951,...,1001.549988,565.450012,1224.599976,4331.899902,163.000000,326.700012,1224.599976,20132.750000,4700.149902,2621.100098
2022-12-26,442.950012,105.000000,732.200012,384.799988,141.300003,3056.050049,380.500000,3428.800049,2091.050049,3716.750000,...,1000.049988,569.299988,1243.300049,4375.350098,165.649994,334.600006,1237.050049,19897.500000,4684.049805,2617.449951
2022-12-27,471.000000,111.150002,764.950012,394.149994,144.800003,3112.600098,386.600006,3477.100098,2124.100098,3769.649902,...,1000.150024,569.799988,1241.050049,4369.250000,165.199997,333.149994,1234.250000,19776.000000,4643.799805,2593.250000
2022-12-28,465.950012,110.000000,761.700012,391.299988,143.899994,3123.699951,387.799988,3446.350098,2121.100098,3797.699951,...,995.000000,568.200012,1242.050049,4385.950195,165.850006,334.399994,1252.349976,19843.599609,4588.649902,2583.600098

In [15]:
assets = df.columns

In [16]:
#Calculate expected annualised returns & sample covariance matrix
mu = expected_returns.mean_historical_return(df)
S = risk_models.sample_cov(df)

In [17]:
#Optimize for max Sharp ratio
ef = EfficientFrontier(mu, S) #Create ef object
weights = ef.max_sharpe()

cleaned_weights = ef.clean_weights()
#print(cleaned_weights)
ef.portfolio_performance(verbose=True)

Expected annual return: 38.4%
Annual volatility: 23.5%
Sharpe Ratio: 1.55

(0.383587788634383, 0.23472967351231283, 1.5489638919269866)

In [18]:
portfolio_val = 
latest_prices = get_latest_prices(df)
weights = cleaned_weights
da = DiscreteAllocation(weights, latest_prices, total_portfolio_value=portfolio_val)
allocation, leftover = da.lp_portfolio()
print('Discrete Allocation: ', allocation)
print('Funds Remaining: ', leftover)

Discrete Allocation:  {'JSWSTEEL.NS': 7, 'ASIANPAINT.NS': 1, 'DIVISLAB.NS': 4, 'ADANIENT.NS': 31, 'BAJFINANCE.NS': 16, 'INFY.NS': 22, 'TITAN.NS': 20, 'RELIANCE.NS': 14, 'POWERGRID.NS': 24, 'BAJAJFINSV.NS': 3, 'BRITANNIA.NS': 16, 'NESTLEIND.NS': 1, 'HINDUNILVR.NS': 14}
Funds Remaining:  28.790996430034284

c:\Users\tempu\AppData\Local\Programs\Python\Python310\lib\site-packages\cvxpy\problems\problem.py:1337: UserWarning: Solution may be inaccurate. Try another solver, adjusting the solver settings, or solve with verbose=True for more information.
  warnings.warn(